Fix PLATFORM_FNS reference issue
ERROR: NameError: name 'PLATFORM_FNS' is not defined (at line 5195)

CAUSE: ULTRA_PLATS and DEEP_PLATS used list(PLATFORM_FNS.keys()) but
PLATFORM_FNS was moved after all functions. These lines executed before
PLATFORM_FNS was defined.

SOLUTION:
1. Set ULTRA_PLATS = [] and DEEP_PLATS = [] initially
2. After PLATFORM_FNS is defined, populate them:
   DEEP_PLATS = list(PLATFORM_FNS.keys())
   ULTRA_PLATS = list(PLATFORM_FNS.keys())

This ensures all references work correctly.